//  Example 5.19, page ???
//  Schaum's Outline of Fundamental of Computing with C++
//  by John R. Hubbard
//  Copyright McGraw-Hill, 1998

#include <iostream.h>

int main()
{ short a[8] = {22, 33, 44, 55, 66, 77, 88, 99};
  cout << a << endl;
  cout << &a[0] << endl;
  cout << &a[1] << endl;
  cout << &a[2] << endl;
  cout << &a[3] << endl;
  cout << &a[4] << endl;
  cout << &a[5] << endl;
  cout << &a[6] << endl;
  cout << &a[7] << endl;
}
