//  Example 5.7, page ???
//  Schaum's Outline of Fundamental of Computing with C++
//  by John R. Hubbard
//  Copyright McGraw-Hill, 1998

#include <iostream.h>

int main()
{ cout << "sizeof(char)   = " << sizeof(char) << endl;
  cout << "sizeof(short)  = " << sizeof(short) << endl;
  cout << "sizeof(int)    = " << sizeof(int) << endl;
  cout << "sizeof(long)   = " << sizeof(long) << endl;
  cout << "sizeof(float)  = " << sizeof(float) << endl;
  cout << "sizeof(double) = " << sizeof(double) << endl;
  return 0;
}
